language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add rustfmt
script:
  - cargo build
  - cargo test
  - cargo fmt -- --check
cache: cargo
